# Rubric

Instructions: DELETE this cell before you submit via a `git push` to your repo before deadline. This cell is for your reference only and is not needed in your report. 

Scoring: Out of 18 points in total.  15 points in the report.  3 points in the video summary of your report for a non-technical audience.

For the report:
- Each Developing  => -0.5 pts
- Each Unsatisfactory/Missing => -1 pts
  - until the score is 0

For the video:
- Developing  => -1.5 pts
- Unsatisfactory/Missing => -3 pts

|                                                                                    | Unsatisfactory                                                                                                                                                                                                                                                                                      | Developing                                                                                                                                                                                                                                                                                                                          | Proficient                                                                                                                                                                                                                                                    | Exellent                                                                                                                                                                                                                                                                                                                                                          |
| ---------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Title & abstract                                                                   | Title or abstract is confusing or fails to offer important details about the question, variables, context, or methods of the project.                                                                                                                                                               | Title or abstract lacks relevance or fails to offer appropriate details about the question, variables, context, or methods of the project.                                                                                                                                                                                          | Title and abstract are relevant, offering sufficient details about the research project.                                                                                                                                                                      | Title and abstract are informative, succinct, and clear. It offers specific details about the question, variables, context, and proposed methods of the study.                                                                                                                                                                                                    |
| Background                                                                         | Did not have at least 3 reliable and relevant sources. Or relevant sources were not used in relevant ways                                                                                                                                                                                           | A key component was not connected to the research literature. Selected literature was from unreliable sources. Literary supports were vague or ambiguous.                                                                                                                                                                           | Key research components were connected to relevant, reliable literature.                                                                                                                                                                                      | Narrative integrates critical and logical details from the peer-reviewed or other professional research literature. Each key research component is grounded to the literature. Attention is given to different perspectives, threats to validity, and opinion vs. evidence.                                                                                       |
| Research question & hypothesis                                                     | Research issue remains unclear. The research purpose, questions, hypotheses, definitions or variables and controls are still largely undefined, or when they are are poorly formed, ambiguous, or not logically connected to the description of the problem. Unclear connections to the literature. | Research issue is identified, but statement is too broad or fails to establish the importance of the problem. The research purpose, questions, hypotheses, definitions or variables and controls are poorly formed, ambiguous, or not logically connected to the description of the problem. Unclear connections to the literature. | Identifies a relevant research issue. Research questions are succinctly stated, connected to the research issue, and supported by the literature. Variables and controls have been identified and described. Connections are established with the literature. | Presents a significant research problem related to the chemical sciences. Articulates clear, reasonable research questions given the purpose, design, and methods of the project. All variables and controls have been appropriately defined. Proposals are clearly supported from the research and theoretical literature. All elements are mutually supportive. |
| Data description                                                                   | Did not have references to relevant data sources for this problem. Did not describe the data obtained at those sources                                                                                                                                                                              | A key data source was not referenced or described in satisfactory level of detail                                                                                                                                                                                                                                                   | All relevant data sources were referenced and described in terms of their key variables and size                                                                                                                                                              | Multiple data sources for each aspect of the project, All data sources are fully described and referenced. The details of the descriptions also make it clear how they support the needs ot the project.                                                                                                                                                          |
| Data wrangling                                                                     | Data obviously not tidy and not clean. Or even if they are clean/tidy, there was no demonstration of that fact                                                                                                                                                                                      | Data has some minor problems with tidiness or cleanliness. Potentially these are not problems but it wasn't fully demonstrated to be the case in the code                                                                                                                                                                           | Data are made tidy and clean, or are clearly demonstrated to be so from download                                                                                                                                                                              | Data wrangling is complete, but also particularly thoroughly done for a very tough case. Often free text parsing is a bear like this, and doing it well can mean a million edge cases.                                                                                                                                                                            |
| Data visualizations                                                                | Many plots don't capture useful information, or their display of information is difficult to understand.. Legends, labels, axes, titles, captions, etc of many plots may be poor or missing. Figures are not referenced in the main text.                                                           | Most plots make sense and capture useful information. Legends, labels, axes, titles, captions, etc are mostly legible and adequately describe the content of the figure. Most figures are referenced or explained inside the main text and not just left hanging.                                                                   | Plots make sense and capture useful information. Legends, labels, axes, titles, captions, etc are clearly legible and adequately describe the content of the figure. Figures are referenced or explained inside the main text and not just left hanging.      | Plots are beautiful and information dense. Legends, labels, axes, titles, captions, etc clearly describe the content of the figure. Figures are well integrated with the text.                                                                                                                                                                                    |
| Data analysis and results                                                          | Lacks any metrics or at least metrics that are relevant to the problem                                                                                                                                                                                                                              | Some metrics selected are not appropriate for the problem or the metrics selected are not described sufficiently                                                                                                                                                                                                                    | All metrics described are appropriate and and described sufficiently                                                                                                                                                                                          | The metrics are described clearly and succinctly. Their appropriateness for addressing the research problem is clearly described.                                                                                                                                                                                                                                 |
| Ethics                                                                             | Only tries a baseline model, never advances to proper model/hyper-parameter selection                                                                                                                                                                                                               | Only investigates one minimal aspect of their problem, e.g. just did a single hyperparameter selection on a single model                                                                                                                                                                                                            | Does a good model/hyper-parameter selection. Only attempts minimal secondary analysis                                                                                                                                                                         | Does a good model/hyper-parameter selection. Performs multiple secondary analysis such as learning curves, heat maps looking at where in the parameter space things are good/bad, uses statistical testing                                                                                                                                                        |
| Conclusion and discussion                                                          | Doesn't have a narrative/conclusions of what the report accomplished. Or very minimal conclusions, like "X was best" without anything else                                                                                                                                                          | Has narrative/conclusions, but it feels perfunctory and lacks context. Especially if the limitations and ethics sections are largely junk or missing                                                                                                                                                                                | Properly recapitulates the results and provides context for them. Has a sense of the limitatins and ethical issues.                                                                                                                                           | Clearly recapitulates the results and provides context, including the literature/background Has a sense of what to do next, and has good explorations of the limitations and ethics.                                                                                                                                                                              |
| Documentation and written communication                                            | Code documentation is non-existent or perfunctory. Writing has usage errors, poor fluency, and poor rhetoric. If doc/writing are both like this you get unsatisfacory. If one is unsatisfactory and the other is developing you still get unsatisfactory overall.                                   | Code documentation is only partially there. Writing has some usage errors, some poor fluency, or some poor rhetoric. If doc/writing are both like this you get developing. If one is developing and the other is satisfactory you still get developing.                                                                             | Code is documented throughout. Writing has good fluency, good rhetoric, and at most a few minor errors.                                                                                                                                                       | Code documentation is highly informative with docstrings. Writing is high quality. If both doc/writing are like this you get excellent. If one is satisfactory and the other excellent you still get satisfactory.                                                                                                                                                |
| Video (developing -1.5 points, unsatisfactory -3 points)                           | Video well outside the 3-5min time range. Does not communicate major results at a non-technical level. Has major technical issues such as no sound or not available at link. Unsatisfactory if 2/3 of these are true                                                                                | Video just outside the 3-5min time range. Does not communicate well on some points (either wrong tech level or just confusing). Has technical issues such as poor speech quality on video. Developing if 2/3 of these are true                                                                                                      | Video has good quality and is in within 3-5 min range. Communicates the major results at an accessible level for non-technical people.                                                                                                                        | Video has high production quality and is in within 3-5 min range. Communicates the major results clearly and gives a sense of the methods at an accessible level for non-technical people. Has a wow factor (e.g. funny or original approach)                                                                                                                     |
| Quality modifier (can result in extra credit beyond 18 points for this assignment) | Almost everything was just barely proficient. Lots of minimal effort work. Do not double punish; if they already lost points on the rubric do not invoke this: -0.5 points                                                                                                                        |                                                                                                                                                                                                                                                                                                                                     |                                                                                                                                                                      |                                                                                                                                                                                                                                                                                                                       More than 5 excellents on this rubric: +0.5 points                                                                                   |

# COGS 108 - Final Project (change this to your project's title)

## Permissions

Place an `X` in the appropriate bracket below to specify if you would like your group's project to be made available to the public, including the names of the authors.

* [  ] YES - make available
* [  ] NO - keep private

## Link to video
https://link.to.your.publicly.viewable.video

## Abstract

Please write one to four paragraphs that describe a very brief overview of why you did this, how you did, and the major findings and conclusions.

## Authors
- Jaidy Leyva: Software, Experimental investigation, Project administration, Writing - original draft, review & editing
- Karen Lie: Software, Data curation, Conceptualization, Visualization
- Lavinia Lim: Conceptualization, Methodology, Analysis, Writing - original draft
- Koushik Karthikeyan: Background research, Software, Analysis, Visualization, Writing - original dr

## Research Question

To what extent are age, sex, race/ethnicity, education and socioeconomic status predictive of disparities in sleep duration (hours per night) and sleep-related impairment (self-reported daytime functional and cognitive limitations), after adjusting for self-reported mental health status, among U.S. adults (18+ years old)?

## Background and Prior Work

Sleep is a core factor in overall health and daily functioning, and public health guidance typically advises <7 hours/night as insufficient sleep for adults.<sup><a href="#ref1" id="cite1">1</a></sup>

National surveillance data show that insufficient sleep is common in the U.S. and also that insufficient sleep differs across demographic groups.
For example, the CDC analysis of the Behavioral Risk Factor Surveillance System found that only about two-thirds of U.S. adults reported “healthy sleep duration” (≥7 hours), with a lower rate among several racial/ethnic minority groups and among adults without higher education, this shows that there is broader concern for the sleep-health of the overall population rather than individual sleep choices.<sup><a href="#ref2" id="cite2">2</a></sup>
Therefore, sleep duration is a population-level concern.<sup><a href="#ref2" id="cite2b">2</a></sup>

A research paper by the National Library of Medicine has investigated why sleep duration varies by age, sex, race/ethnicity, and socioeconomic status. The medical reviews emphasize that “race/ethnicity” is a social category that can include potential exposures—such as discrimination, poor neighborhood conditions, and working constraints—that ultimately play a role in sleep opportunity and timing.<sup><a href="#ref3" id="cite3">3</a></sup>
Large U.S. survey studies show that disparities stay even after accounting for many variables. For instance, an NHIS trends analysis reported increases in self-reported short sleep in recent years that were especially pronounced among Black and Hispanic adults even after adjusting for demographic and socioeconomic factors, raising concern that widening sleep disparities may lead to other health inequalities over time.<sup><a href="#ref4" id="cite4">4</a></sup>
Longitudinal evidence also suggests that short sleep is more common in lower income/education groups and among some racial/ethnic minority groups, with socioeconomic context and living conditions explaining more of the disparity than individual health behaviors alone.<sup><a href="#ref5" id="cite5">5</a></sup>

Importantly, the consequences of insufficient sleep extend beyond “hours slept” to sleep-related impairment—fatigue, excessive daytime sleepiness, and reduced functioning.
Research that took into account both sleep duration and symptoms found that lack of sleep is associated with higher levels of fatigue and daytime sleepiness, and that both education and race/ethnicity relate to multiple sleep-related symptoms, underscoring that disparities may appear in both sleep quantity and daytime impact.<sup><a href="#ref6" id="cite6">6</a></sup>
Additionally, Mental health is central to this question because it is strongly connected with overall sleep health: evidence supports relationships between sleep disturbances and depression/anxiety, and anxiety can also cause excessive daytime sleepines.<sup><a href="#ref7" id="cite7">7</a></sup>
Also, consistent with that, NHIS-based analysis showed that psychological distress is directly associated with unhealthy sleep duration even after adjusting for socioeconomic factors and health conditions.<sup><a href="#ref8" id="cite8">8</a></sup>
Together, the research shows the importance of our project's focus on estimating how age, sex, race/ethnicity, and socioeconomic status relate to both sleep duration and sleep-related impairment.

References:

<a name="ref1"></a><a href="#cite1">^</a> Centers for Disease Control and Prevention (CDC). FastStats: Sleep in Adults (May 15, 2024). https://www.cdc.gov/sleep/data-research/facts-stats/adults-sleep-facts-and-stats.html

<a name="ref2"></a><a href="#cite2">^</a> Liu Y, Wheaton AG, Chapman DP, Cunningham TJ, Lu H, Croft JB. Prevalence of Healthy Sleep Duration among Adults — United States, 2014. MMWR (2016). https://www.cdc.gov/mmwr/volumes/65/wr/mm6506a1.htm

<a name="ref3"></a><a href="#cite3">^</a> Grandner MA. Sleep disparity, race/ethnicity, and socioeconomic position. Sleep Medicine (2015). https://pmc.ncbi.nlm.nih.gov/articles/PMC4631795/

<a name="ref4"></a><a href="#cite4">^</a> Sheehan CM, Frochen SE, Walsemann KM, Ailshire JA. Are U.S. adults reporting less sleep? Findings from sleep duration trends in the National Health Interview Survey, 2004–2017. (2018). https://pmc.ncbi.nlm.nih.gov/articles/PMC6941709/

<a name="ref5"></a><a href="#cite5">^</a> Stamatakis KA, Kaplan GA, Roberts RE. Short Sleep Duration across Income, Education and Race/Ethnic Groups: Population Prevalence and Growing Disparities over 34 Years of Follow-Up. (2007). https://pmc.ncbi.nlm.nih.gov/articles/PMC2140008/

<a name="ref6"></a><a href="#cite6">^</a> Cunningham TJ, Ford ES, Chapman DP, Liu Y, Croft JB. Independent and joint associations of race/ethnicity and educational attainment with sleep-related symptoms in a population-based US sample. Preventive Medicine (2015/2016). https://stacks.cdc.gov/view/cdc/38169

<a name="ref7"></a><a href="#cite7">^</a> Alvaro PK, Roberts RM, Harris JK. A systematic review assessing bidirectionality between sleep disturbances, anxiety, and depression. SLEEP (2013). https://pmc.ncbi.nlm.nih.gov/articles/PMC3669059/

<a name="ref8"></a><a href="#cite8">^</a> Seixas AA, Nunes JV, Airhihenbuwa CO, et al. Linking emotional distress to unhealthy sleep duration: analysis of the 2009 National Health Interview Survey. (2015). https://pmc.ncbi.nlm.nih.gov/articles/PMC4590582/

## Hypothesis

We hypothesize that age, sex, race/ethnicity, and socioeconomic status will be significantly associated with sleep duration and sleep-related impairment among U.S. adults, even after adjusting for self-reported mental health status. Specifically, individuals from lower socioeconomic backgrounds and racial/ethnic minority groups are expected to report shorter sleep duration and greater sleep-related impairment. This hypothesis is based on prior research showing that social and structural factors influence both sleep health and access to resources that support healthy sleep.

## Data

### Data overview

- National Health and Nutrition Examination Survey (NHANES) August 2021 – August 2023
  - https://wwwn.cdc.gov/nchs/nhanes/continuousnhanes/default.aspx
  - 5218 observations
  - 57 variables total variables (8 used)
  - Participant identifier, Age (years), Gender, Sleep Hours, Race/ethnicity, Income Ratio, Mental Health Score
  - NHANES is cross-sectional, it does'nt allow for causal inference or longitudinal analysis. Many variables also require careful cleaning due to special codes used for missing responses.
- Behavioral Risk Factor Surveillance System (BRFSS) 2022 Data
  - https://www.cdc.gov/brfss/annual_data/2022/files/LLCP2022XPT.zip
  - 445,132 observations
  - 326 variables (9 used)
  - Sleep Duration (in hrs), Age (years), Sex, Race/ethnicity, Education Level, Income, Mental health days, Functional and Cognitive impairment
  - The BRFSS relies on self-reported sleep and mental health measures and is limited to adults, which may introduce recall bias and restrict generalizability to younger populations. Additionally, the cross-sectional design precludes causal inference.

In [3]:
%load_ext autoreload
%autoreload 2

In [4]:
import sys
sys.path.append('./modules')
import get_data
datafiles = [
    { 'url': 'https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/DEMO_L.xpt', 'filename':'DEMO_L.xpt'},
    { 'url': 'https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/SLQ_L.xpt', 'filename':'SLQ_L.xpt'},
    { 'url': 'https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/DPQ_L.xpt', 'filename':'DPQ_L.xpt'},
    {
        "url": "https://wwwn.cdc.gov/Nchs/Data/Nnyfs/Public/2012/DataFiles/Y_DEMO.xpt",
        "filename": "Y_DEMO.xpt",
    },
    {'url': 'https://www.cdc.gov/brfss/annual_data/2022/files/LLCP2022XPT.zip', 'filename': 'LLCP2022XPT.zip'},
]

get_data.get_raw(datafiles,destination_directory='data/00-raw/')

Overall Download Progress:   0%|          | 0/5 [00:00<?, ?it/s]
Downloading DEMO_L.xpt: 0.00B [00:00, ?B/s]
Downloading DEMO_L.xpt: 2.31MB [00:00, 22.8MB/s]
Overall Download Progress:  20%|██        | 1/5 [00:00<00:02,  1.47it/s]

Successfully downloaded: DEMO_L.xpt

Downloading SLQ_L.xpt: 0.00B [00:00, ?B/s]
Overall Download Progress:  40%|████      | 2/5 [00:00<00:01,  2.15it/s]

Successfully downloaded: SLQ_L.xpt

Downloading DPQ_L.xpt: 0.00B [00:00, ?B/s]
Overall Download Progress:  60%|██████    | 3/5 [00:01<00:00,  2.58it/s]

Successfully downloaded: DPQ_L.xpt

Downloading Y_DEMO.xpt: 0.00B [00:00, ?B/s]
Downloading Y_DEMO.xpt: 280kB [00:00, 1.33MB/s]
Overall Download Progress:  80%|████████  | 4/5 [00:02<00:00,  1.91it/s]

Successfully downloaded: Y_DEMO.xpt

Downloading LLCP2022XPT.zip:   0%|          | 0.00/84.6M [00:00<?, ?B/s]
Downloading LLCP2022XPT.zip:   3%|▎         | 2.66M/84.6M [00:00<00:03, 26.6MB/s]
Downloading LLCP2022XPT.zip:  14%|█▍        | 12.1M/84.6M [00:00<00:01, 66.2MB/s]
Downloading LLCP2022XPT.zip:  26%|██▌       | 21.6M/84.6M [00:00<00:00, 79.6MB/s]
Downloading LLCP2022XPT.zip:  39%|███▊      | 32.7M/84.6M [00:00<00:00, 92.1MB/s]
Downloading LLCP2022XPT.zip:  53%|█████▎    | 44.9M/84.6M [00:00<00:00, 103MB/s]
Downloading LLCP2022XPT.zip:  65%|██████▌   | 55.2M/84.6M [00:00<00:00, 88.4MB/s]
Downloading LLCP2022XPT.zip:  76%|███████▌  | 64.3M/84.6M [00:00<00:00, 57.9MB/s]
Downloading LLCP2022XPT.zip:  85%|████████▍ | 71.5M/84.6M [00:01<00:00, 44.3MB/s]
Downloading LLCP2022XPT.zip:  93%|█████████▎| 78.5M/84.6M [00:01<00:00, 48.8MB/s]
Downloading LLCP2022XPT.zip: 100%|█████████▉| 84.6M/84.6M [00:01<00:00, 50.4MB/s]
Overall Download Progress: 100%|██████████| 5/5 [00:03<00:00,  1.36it/s]

Successfully downloaded: LLCP2022XPT.zip

### NHANES August 2021 - August 2023 Data ###

This study uses data from the National Health and Nutrition Examination Survey (NHANES), a nationally representative survey of U.S. adults. The analytic dataset was created by merging demographic, sleep questionnaire, and mental questionnaire components. After cleaning and restricting to complete cases, the final sample includes adults with valid data on sleep duration, socioeconomic characteristics, and mental health.

The primary outcome is sleep duration, measured as the number of hours usually slept on weekdays or workdays. Sleep is reported in hours and ranges approximately from 2 to 14 hours in the cleaned dataset. It is top coded at 14 and bottom coded at 2. A value of 2 indicates less than 3 hours of sleep while a value of 14 indicates 14 or more hours of sleep. Short sleep is typically defined as fewer than 7 hours per night and is associated with increased health risks. Mental health was measured using a mental health score, which comprises of nine depression factors with responses scored from 0 (not at all) to 3 (nearly every day). The mental health score ranges from 0 to 27, with higher scores indicating more severe depressive symptoms.

Key predictors include age (years), sex (male/female), race/ethnicity (categorized groups), education level (less than 9th grade to college graduate or above), and income-to-poverty ratio. The income-to-poverty ratio is a continuous measure comparing family income to the poverty threshold. Values below 1 indicate income below the poverty line.

Some limitations should be considered. Sleep and mental health measures are self-reported, so participants may not remember their experiences perfectly or may underreport or overreport symptoms. Additionally, only participants with complete data were included, which could affect results if missing data are not random. Despite these limitations, NHANES is a large and nationally representative dataset that is appropriate for examining differences in sleep duration across demographic and socioeconomic groups.

In [5]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION 
import pandas as pd
import numpy as np

demo = pd.read_sas('data/00-raw/DEMO_L.xpt')
sleep = pd.read_sas('data/00-raw/SLQ_L.xpt')
mental = pd.read_sas('data/00-raw/DPQ_L.xpt')

# Merging demographic, mental health, and sleep data to one Dataframe
df1 = demo.merge(sleep, on="SEQN", how="inner")
df1 = df1.merge(mental, on="SEQN", how="inner")

#Keeping only variables needed
columns_keep = ["SEQN","SLD012","RIDAGEYR","RIAGENDR", "RIDRETH3","INDFMPIR", "DMDEDUC2","DPQ010","DPQ020","DPQ030","DPQ040","DPQ050","DPQ060","DPQ070","DPQ080","DPQ090"]
df1 = df1[columns_keep]


# Pre-clean data summary
print("\nDataset size BEFORE cleaning:")
print(f"Observations (rows): {df1.shape[0]}")
print(f"Variables (cols): {df1.shape[1]}")

missing_summary = pd.DataFrame({
    "missing_count": df1.isna().sum(),
    "missing_percent": (df1.isna().mean() * 100).round(2)
}).sort_values("missing_percent", ascending=False)

print("\nMissingness summary (before cleaning):")
print(missing_summary)

# Flag outliers / suspicious entries 
print("\nPotential outliers / suspicious checks (before cleaning):")

# NHANES codebook notes values typically 3 to 13.5; 2 and 14 are top/bottom codes
sleep_outliers = df1[(df1["SLD012"].notna()) & ((df1["SLD012"] < 2) | (df1["SLD012"] > 14.0))]
print("Sleep outliers count (outside 3–14.0):", sleep_outliers.shape[0])

dpq_cols = ["DPQ010","DPQ020","DPQ030","DPQ040","DPQ050","DPQ060","DPQ070","DPQ080","DPQ090"]
# Mental health total score should be 0–27
for col in dpq_cols:
    print(col, "outliers count:", df1[df1[col] > 3].shape[0])

# Age (0-79); top coded at 80
age_outliers = df1[(df1["RIDAGEYR"].notna()) & ((df1["RIDAGEYR"] < 0))]
print("Age outliers count:", age_outliers.shape[0])

# Income ratio top coded at 5.00
income_outliers = df1[(df1["INDFMPIR"].notna()) & (df1["INDFMPIR"] < 0)]
print("Income ratio outliers count:", income_outliers.shape[0])

#CLEANING

#Add up all the depression data into one score
df1[dpq_cols] = df1[dpq_cols].replace({7: np.nan, 9: np.nan})
df1["mental_health_score"] = df1[dpq_cols].sum(axis=1)
df1["mental_health_score"] = df1["mental_health_score"].astype(int)
df1 = df1.drop(columns=dpq_cols)

#Rename columns
df1 = df1.rename(columns={
    "SEQN": "participant_id",
    "SLD012": "sleep_hours",
    "RIDAGEYR": "age",
    "RIAGENDR": "gender",
    "RIDRETH3": "race_ethnicity",
    "INDFMPIR": "income_ratio",
    "DMDEDUC2": "education"})

#Convert age and participant id to integer
df1["participant_id"] = df1["participant_id"].astype(int)
df1["age"] = df1["age"].astype(int)
df1["race_ethnicity"] = df1["race_ethnicity"].astype(int)


# Recode RIDRETH3 (race/ethnicity) into descriptive category labels
# Original NHANES numeric codes are converted to categorical values

race_map = {
    1: "Mexican American",
    2: "Other Hispanic",
    3: "Non-Hispanic White",
    4: "Non-Hispanic Black",
    6: "Non-Hispanic Asian",
    7: "Other/Multi"
}
df1["race_ethnicity"] = df1["race_ethnicity"].map(race_map)

# Keep only valid education levels (remove "Refused" and "Don't Know" responses)
df1 = df1[df1["education"].isin([1,2,3,4,5])]

# Recode DMDEDUC2 (education) into descriptive category labels
# Original NHANES numeric codes are converted to categorical values

education_map = {
    1: "Less than 9th grade",
    2: "9–11th grade",
    3: "High school/GED",
    4: "Some college/AA",
    5: "College graduate or above"
}
df1["education"] = df1["education"].map(education_map)

# Recode RIAGENDR (gender) into descriptive category labels
# Original NHANES numeric codes are converted to categorical values
gender_map = {
    1: "Male",
    2: "Female"
}
df1["gender"] = df1["gender"].map(gender_map)

#Remove rows with NaN values
df1 = df1.dropna()

#After Cleaning Summary

print("\nDataset size AFTER cleaning:")
print(f"Observations (rows): {df1.shape[0]}")
print(f"Variables (cols): {df1.shape[1]}")

missing_summary = pd.DataFrame({
    "missing_count": df1.isna().sum(),
    "missing_percent": (df1.isna().mean() * 100).round(2)
}).sort_values("missing_percent", ascending=False)

print("\nMissingness summary (after cleaning):")
print(missing_summary)

# Flag outliers / suspicious entries 
print("\nPotential outliers / suspicious checks (after cleaning):")

# NHANES codebook notes values typically 3 to 13.5; 2 and 14 are top/bottom codes
sleep_outliers = df1[(df1["sleep_hours"].notna()) & ((df1["sleep_hours"] < 2) | (df1["sleep_hours"] > 14.0))]
print("Sleep outliers count (outside 2–14.0):", sleep_outliers.shape[0])

# Mental health total score should be 0–27
mh_outliers = df1[(df1["mental_health_score"].notna()) & ((df1["mental_health_score"] < 0) | (df1["mental_health_score"] > 27))]
print("Mental health score outliers count:", mh_outliers.shape[0])

# Age (0-79); top coded at 80
age_outliers = df1[(df1["age"].notna()) & ((df1["age"] < 0))]
print("Age outliers count:", age_outliers.shape[0])

# Income ratio top coded at 5.00
income_outliers = df1[(df1["income_ratio"].notna()) & (df1["income_ratio"] < 0)]
print("Income ratio outliers count:", income_outliers.shape[0])

print("Observations:", df1.shape[0])
print("Variables:", df1.shape[1])
df1.to_csv("data/02-processed/nhanes2123_final.csv", index=False)

df1.head()

Dataset size BEFORE cleaning:
Observations (rows): 6337
Variables (cols): 16

Missingness summary (before cleaning):
          missing_count  missing_percent
INDFMPIR            831            13.11
DPQ090              831            13.11
DPQ070              829            13.08
DPQ080              829            13.08
DPQ060              827            13.05
DPQ050              824            13.00
DPQ040              823            12.99
DPQ030              821            12.96
DPQ020              819            12.92
DPQ010              818            12.91
DMDEDUC2            273             4.31
SLD012               65             1.03
SEQN                  0             0.00
RIDAGEYR              0             0.00
RIAGENDR              0             0.00
RIDRETH3              0             0.00

Potential outliers / suspicious checks (before cleaning):
Sleep outliers count (outside 3–14.0): 0
DPQ010 outliers count: 21
DPQ020 outliers count: 10
DPQ030 outliers count: 7
DPQ040 outliers count: 8
DPQ050 outliers count: 3
DPQ060 outliers count: 5
DPQ070 outliers count: 3
DPQ080 outliers count: 12
DPQ090 outliers count: 5
Age outliers count: 0
Income ratio outliers count: 0

Dataset size AFTER cleaning:
Observations (rows): 5218
Variables (cols): 8

Missingness summary (after cleaning):
                     missing_count  missing_percent
participant_id                   0              0.0
sleep_hours                      0              0.0
age                              0              0.0
gender                           0              0.0
race_ethnicity                   0              0.0
income_ratio                     0              0.0
education                        0              0.0
mental_health_score              0              0.0

Potential outliers / suspicious checks (after cleaning):
Sleep outliers count (outside 2–14.0): 0
Mental health score outliers count: 0
Age outliers count: 0
Income ratio outliers count: 0
Observations: 5218
Variables: 8

,participant_id,sleep_hours,age,gender,race_ethnicity,income_ratio,education,mental_health_score
0,130378,9.5,43,Male,Non-Hispanic Asian,5.00,College graduate or above,0
1,130379,9.0,66,Male,Non-Hispanic White,5.00,College graduate or above,1
2,130380,8.0,44,Female,Other Hispanic,1.41,High school/GED,2
3,130386,7.5,34,Male,Mexican American,1.33,Some college/AA,1
4,130387,3.0,68,Female,Non-Hispanic White,1.32,College graduate or above,0

## Behavioral Risk Factor Surveillance System (BRFSS) 2022

The Behavioral Risk Factor Surveillance System (BRFSS) 2022 dataset contains health-related risk behaviors, chronic health conditions, preventive service use, and sleep information for adults in the United States. BRFSS is conducted annually by the Centers for Disease Control and Prevention (CDC) as a nationally representative, state-based telephone survey. The 2022 dataset provides cross-sectional data used to monitor population health and examine disparities across states and demographic groups.

Key variables include demographic characteristics (age, sex, race/ethnicity, education, income), health behaviors (smoking, alcohol use, physical activity), and health status indicators (e.g., diabetes, hypertension, obesity, general health). Age is recorded in years for adults aged 18 and older, while most other variables are categorical. Importantly, BRFSS 2022 includes a sleep duration measure that asks respondents how many hours of sleep they get in a 24-hour period. This numeric variable (typically 1–24 hours) can be analyzed continuously or categorized to identify short sleep duration (commonly defined as fewer than 7 hours). While it captures sleep quantity, it does not assess sleep quality or diagnosed sleep disorders.

Several data quality considerations apply. Because BRFSS data are self-reported, responses may be affected by recall or social desirability bias. Missing data may result from nonresponse or skipped questions and may not be random. Additionally, BRFSS uses a complex sampling design with weighting, so analyses must apply survey weights to obtain nationally representative estimates. As a cross-sectional survey of noninstitutionalized adults, findings cannot establish causality.

Overall, the dataset provides a structured and comprehensive foundation for analyzing adult health behaviors, chronic disease, sleep duration, and health disparities in the United States.

In [6]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION 
import pandas as pd
import zipfile
with zipfile.ZipFile('./data/00-raw/LLCP2022XPT.zip', 'r') as z:
    print("Files inside zip:", z.namelist())
    z.extractall('./data/00-raw/')

brfss = pd.read_sas('./data/00-raw/LLCP2022XPT.zip', format="xport")

print("\n=== BRFSS SLEEP columns ===")
sleep_cols_brfss = [col for col in brfss.columns if 'SLP' in col.upper() or 'SLEEP' in col.upper() or 'SLEPT' in col.upper()]
print(sleep_cols_brfss)

Files inside zip: ['LLCP2022.XPT ']

=== BRFSS SLEEP columns ===
['SLEPTIM1']

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


brfss_raw = pd.read_sas('data/00-raw/LLCP2022.XPT ', format='xport')
brfss_raw.columns = [c.upper() for c in brfss_raw.columns]
print("Total raw observations:", brfss_raw.shape[0])

# ---- Select variables ----
# SLEPTIM1  = sleep hours per night (PRIMARY outcome)
# DIFFALON  = physical/functional limitation (difficulty doing errands alone)
# CNCRDIFF = cognitive limitation (difficulty concentrating or remembering) 
# SEXVAR    = sex
# _AGEG5YR  = age group (5-year bands)
# _IMPRACE  = imputed race/ethnicity
# INCOME3   = household income (SES proxy)
# EDUCA     = education level (SES proxy)
# MENTHLTH  = poor mental health days past 30 (covariate)

cols_wanted = [
    "SLEPTIM1",
    "DIFFALON",
    "CNCRDIFF",
    "SEXVAR",
    "_AGEG5YR",
    "_IMPRACE",
    "INCOME3",
    "EDUCA",
    "MENTHLTH",
]

#keeps existing columns
cols_available = [c for c in cols_wanted if c in brfss_raw.columns]
cols_missing   = [c for c in cols_wanted if c not in brfss_raw.columns]
print("Columns found:  ", cols_available)
print("Columns missing:", cols_missing)

df = brfss_raw[cols_available].copy()

def num(s):
    return pd.to_numeric(s, errors="coerce")

#clean variables
# Sleep hours (1–24 valid; 77=don't know, 99=refused → NaN)
df["sleep_hours"] = num(df["SLEPTIM1"])
df.loc[df["sleep_hours"] > 24, "sleep_hours"] = np.nan
df.loc[df["sleep_hours"] < 1,  "sleep_hours"] = np.nan

# Physical daytime impairment — difficulty doing errands alone
df["functional_impairment"] = num(df["DIFFALON"]).map({1: 1, 2: 0})

# Cognitive impairment — binary (0=no difficulty, 1=any difficulty) to make it easier to comapre w functional impairment
df["cognitive_impairment"] = num(df["CNCRDIFF"]).map({
    1: 0,  # no difficulty
    2: 1,  # some difficulty → impaired
    3: 1,  # a lot of difficulty → impaired
    7: np.nan,
    9: np.nan
})

# Sex (matches teammates' male/female coding)
df["sex"] = num(df["SEXVAR"]).map({
    1: "male",
    2: "female",
})

# Age group — BRFSS uses 5-year bands (matches youth/adult split from teammates)
age_map = {
    1: "18-24",  2: "25-29",  3: "30-34",  4: "35-39",
    5: "40-44",  6: "45-49",  7: "50-54",  8: "55-59",
    9: "60-64", 10: "65-69", 11: "70-74", 12: "75-79",
    13: "80+"
}
df["age_group"] = num(df["_AGEG5YR"]).map(age_map)

# Youth flag (matches teammates' Y_DEMO youth dataset focus)
df["is_youth"] = num(df["_AGEG5YR"]).apply(
    lambda x: True if x == 1 else (False if pd.notna(x) else np.nan)
)

# Race/ethnicity (matches teammates' race_ethnicity naming convention)
race_map = {
    1: "non_hispanic_white",
    2: "non_hispanic_black",
    3: "non_hispanic_asian",
    4: "non_hispanic_other",
    5: "hispanic",
    6: "multiracial",
}
df["race_ethnicity"] = num(df["_IMPRACE"]).map(race_map)

# Income — SES proxy (77=don't know, 99=refused → NaN)
df["income"] = num(df["INCOME3"])
df.loc[df["income"] >= 77, "income"] = np.nan

# Education — SES proxy (9=refused → NaN)
# Matches teammates' education levels
education_map = {
    1: "never_attended",
    2: "elementary",
    3: "some_high_school",
    4: "high_school_grad",
    5: "some_college",
    6: "college_grad",
}
df["education"] = num(df["EDUCA"]).map(education_map)
df.loc[num(df["EDUCA"]) == 9, "education"] = np.nan

# Mental health days — covariate (88=none→0, 77/99=refused/dk → NaN)
df["mental_health_days"] = num(df["MENTHLTH"])
df.loc[df["mental_health_days"] == 88, "mental_health_days"] = 0
df.loc[df["mental_health_days"] >= 77,  "mental_health_days"] = np.nan


#Pre-clean summary
print("\nDataset size BEFORE cleaning:")
print(f"Observations (rows): {df.shape[0]}")
print(f"Variables (cols):    {df.shape[1]}")

missing_summary = pd.DataFrame({
    "missing_count":   df.isna().sum(),
    "missing_percent": (df.isna().mean() * 100).round(2)
}).sort_values("missing_percent", ascending=False)
print("\nMissingness summary (before cleaning):")
print(missing_summary)

#Outlier checks
print("\nOutlier checks (before cleaning):")
sleep_out = df[(df["sleep_hours"].notna()) & 
               ((df["sleep_hours"] < 1) | (df["sleep_hours"] > 24))]
print("Sleep outliers:", sleep_out.shape[0])

mh_out = df[(df["mental_health_days"].notna()) & 
            ((df["mental_health_days"] < 0) | (df["mental_health_days"] > 30))]
print("Mental health days outliers:", mh_out.shape[0])

#Tidy dataset
keep_cols = [
    "sleep_hours",
    "functional_impairment",
    "cognitive_impairment",
    "sex",
    "age_group",
    "is_youth",
    "race_ethnicity",
    "income",
    "education",
    "mental_health_days",
]
keep_cols = [c for c in keep_cols if c in df.columns]
df_clean = df[keep_cols].dropna()

#post-clean summary
print("\nDataset size AFTER cleaning:")
print(f"Observations (rows): {df_clean.shape[0]}")
print(f"Variables (cols):    {df_clean.shape[1]}")

missing_summary_after = pd.DataFrame({
    "missing_count":   df_clean.isna().sum(),
    "missing_percent": (df_clean.isna().mean() * 100).round(2)
}).sort_values("missing_percent", ascending=False)
print("\nMissingness summary (after cleaning):")
print(missing_summary_after)

print("\nObservations:", df_clean.shape[0])
print("Variables:",    df_clean.shape[1])

df_clean.to_csv('data/02-processed/brfss2022_sleep_clean.csv', index=False)
df_clean.head()

Total raw observations: 445132
Columns found:   ['SLEPTIM1', 'DIFFALON', 'CNCRDIFF', 'SEXVAR', '_AGEG5YR', '_IMPRACE', 'INCOME3', 'EDUCA', 'MENTHLTH']
Columns missing: []

Dataset size BEFORE cleaning:
Observations (rows): 445132
Variables (cols):    19

Missingness summary (before cleaning):
                       missing_count  missing_percent
cognitive_impairment          422549            94.93
CNCRDIFF                      421733            94.74
income                         96047            21.58
functional_impairment          25656             5.76
DIFFALON                       23942             5.38
INCOME3                        12932             2.91
mental_health_days              9067             2.04
age_group                       9079             2.04
sleep_hours                     5453             1.23
education                       2383             0.54
MENTHLTH                           3             0.00
EDUCA                              5             0.00
_IMPRACE                           0             0.00
sex                                0             0.00
_AGEG5YR                           0             0.00
is_youth                           0             0.00
race_ethnicity                     0             0.00
SEXVAR                             0             0.00
SLEPTIM1                           3             0.00

Outlier checks (before cleaning):
Sleep outliers: 0
Mental health days outliers: 0

Dataset size AFTER cleaning:
Observations (rows): 17791
Variables (cols):    10

Missingness summary (after cleaning):
                       missing_count  missing_percent
sleep_hours                        0              0.0
functional_impairment              0              0.0
cognitive_impairment               0              0.0
sex                                0              0.0
age_group                          0              0.0
is_youth                           0              0.0
race_ethnicity                     0              0.0
income                             0              0.0
education                          0              0.0
mental_health_days                 0              0.0

Observations: 17791
Variables: 10

,sleep_hours,functional_impairment,cognitive_impairment,sex,age_group,is_youth,race_ethnicity,income,education,mental_health_days
20558,7.0,0.0,1.0,female,75-79,False,non_hispanic_white,5.0,college_grad,10.0
20565,7.0,1.0,0.0,female,75-79,False,non_hispanic_white,8.0,college_grad,0.0
20578,8.0,0.0,0.0,male,70-74,False,non_hispanic_white,7.0,college_grad,30.0
20579,7.0,1.0,0.0,female,65-69,False,non_hispanic_black,2.0,some_college,10.0
20581,6.0,0.0,0.0,female,75-79,False,non_hispanic_white,6.0,college_grad,5.0

## Results

### Exploratory Data Analysis

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your EDA feedback

**NOTE** The final report should not be overly long.  If this EDA step is huge and complicated  and you went down a lot of dead ends, then you should do something about that.  Some options... 

1) remove any EDA you later decided was unecessary side quest.
2) if the code to EDA is very long (in either lines or in time to compute) make sure you write out images of the EDA into `results/` and reload them as images here instead of recalculating it. And make a statement here like "To see the code responsible for EDA analyses see `02-EDACheckpoint.ipynb`."

### Summary Statistics
To better understand the characteristics of the dataset, we begin with summary statistics for several key variables, including sleep duration, age, income-to-poverty ratio, and mental health score. Examining these descriptive statistics provides an overview of the central tendencies, variability, and ranges of the variables included in the analysis. This helps identify general patterns in the data and ensures that the variables fall within reasonable ranges before conducting further exploratory analysis and visualizations.

In [ ]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION
import numpy as np
import pandas as pd
import os

df1.to_csv("data/02-processed/nhanes2123_final.csv", index=False)
df_clean.to_csv('data/02-processed/brfss2022_sleep_clean.csv', index=False)

In [ ]:
df1 = pd.read_csv("data/02-processed/nhanes2123_final.csv")
df1[["sleep_hours", "age", "income_ratio", "mental_health_score"]].describe()

### Second Analysis You Did - Give it a better title

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.  Every project will be different here... but some examples of analyses are: inferential statistics where you calculate p-values (like a t-test or a Monte Carlo simulation), regression models, or a machine learning model

In [ ]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

### ETC AD NASEUM

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [ ]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

## Ethics

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Discusison and Conclusion

Wrap it all up here.  Somewhere between 3 and 10 paragraphs roughly. 
1. Summarize the important results you made
2. This is a good time to refer back to your Background section and review how this work extended the previous stuff.
3. Try to bring all the different results together into a bigger picture... what have we learned?
4. Often what we learned is confusing.  Discuss if there are contradictory results how that might have happened
5. Discuss the limitations of your work. e.g, is the dataset a biased sample? would more data make you more confident? would longitudinal instead of cross-sectional data helpful? is there evidence that the phenomena you're investigating may change over time? etc
6. If you would like, you can also say what the next steps in this investigation might be if the work was to continue outside this class